### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by fgogrrore4ft3w** [YuzheZhang-1999/DiffTSR#21]
(DiffTSR) C:\Users\L\Pictures\DiffTSR>python inference_DiffTSR.py
Traceback (most recent call last):
  File "inference_DiffTSR.py", line 13, in <module>
    DiffTSR_model.load_model(DiffTSR_ckpt_config)
  File "C:\Users\L\Pictures\DiffTSR\model\DiffTSR.py", line 50, in load_model
    state_dict = torch.load(path, map_location=self.device)
  File "C:\Users\L\anaconda3\envs\DiffTSR\lib\site-packages\torch\serialization.py", line 594, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "C:\Users\L\anaconda3\envs\DiffTSR\lib\site-packages\torch\serialization.py", line 853, in _load
    result = unpickler.load()
  File "C:\Users\L\anaconda3\envs\DiffTSR\lib\site-packages\torch\serialization.py", line 845, in persistent_load
    load_tensor(data_type, size, key, _maybe_decode_ascii(location))
  File "C:\Users\L\anaconda3\envs\DiffTSR\lib\site-packages\torch\serialization.py", line 834, in load_tensor
    loaded_storages[key] = restore_location(storage, location)
  File "C:\Users\L\anaconda3\envs\DiffTSR\lib\site-packages\torch\serialization.py", line 811, in restore_location
    return default_restore_location(storage, map_location)
  File "C:\Users\L\anaconda3\envs\DiffTSR\lib\site-packages\torch\serialization.py", line 175, in default_restore_location
    result = fn(storage, location)
  File "C:\Users\L\anaconda3\envs\DiffTSR\lib\site-packages\torch\serialization.py", line 157, in _cuda_deserialize
    return obj.cuda(device)
  File "C:\Users\L\anaconda3\envs\DiffTSR\lib\site-packages\torch\_utils.py", line 79, in _cuda
    return new_type(self.size()).copy_(self, non_blocking)
  File "C:\Users\L\anaconda3\envs\DiffTSR\lib\site-packages\torch\cuda\__init__.py", line 462, in _lazy_new
    return super(_CudaBase, cls).__new__(cls, *args, **kwargs)
RuntimeError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 6.00 GiB total capacity; 5.19 GiB already allocated; 0 bytes free; 5.34 GiB reserved in total by PyTorch)

(DiffTSR) C:\Users\L\Pictures\DiffTSR>

what do you recommend for this situation ?

**Comment by huangguifeng** [comment]
有推理成功吗。需要多少显存？我用8G也不够。

**Comment by 4C4247** [comment]
> 有推理成功吗。需要多少显存？我用8G也不够。

用服务器跑推理看看找个大显存的，推理很快的。

**Comment by YuzheZhang-1999** [comment]
本实验均跑在NVIDIA A100-40GB集群上。
建议使用显存大于12GB的显卡。
